# Generated by Django 3.2.5 on 2021-07-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='status',
            order_with_respect_to=None,
        ),
    ]
